Traceback (most recent call last):
  File "/usr/share/miniconda/envs/duke-msec-bootcamp/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/envs/duke-msec-bootcamp/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/envs/duke-msec-bootcamp/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/envs/duke-msec-bootcamp/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/envs/duke-msec-bootcamp/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/envs/duke-msec-bootcamp/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda/envs/duke-msec-bootcamp/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import os
import sys
import pandas as pd
import numpy as np
from sklearn.model_selection import TimeSeriesSplit
import yaml
import fitz  # PyMuPDF
from PIL import Image
from IPython.display import display
import plotly
plotly.offline.init_notebook_mode()

# setup src path
sys.path.append(os.path.join(os.path.dirname("../"), "src"))

# Load the data
import utils
from utils import cols, theme
import graphing
import arbitrage
import investments
import descriptive_statistics

from IPython.core.display import HTML
HTML("""
<style>
.output_png {
    display: table-cell;
    text-align: center;
    vertical-align: middle;
}
</style>
""")

utils.load_env(path="../.env")
utils.load_variables(path="../variables.yml")

df = pd.read_csv(os.path.join(os.getenv("LOCAL_DATA_PATH"), os.getenv("FOOD_PRICES_FILENAME")))
df = utils.clean_data(df)
pdf = fitz.open(os.path.join(os.getenv("LOCAL_DATA_PATH"), os.getenv("PDF_EXERCISE_THREE_FILENAME")))
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 17[0m
[1;32m     14[0m sys[38;5;241m.[39mpath[38;5;241m.[39mappend(os[38;5;241m.[39mpath[38;5;241m.[39mjoin(os[38;5;241m.[39mpath[38;5;241m.[39mdirname([38;5;124m"[39m[38;5;124m../[39m[38;5;124m"[39m), [38;5;124m"[39m[38;5;124msrc[39m[38;5;124m"[39m))
[1;32m     16[0m [38;5;66;03m# Load the data[39;00m
[0;32m---> 17[0m [38;5;28;01mimport[39;00m [38;5;21;01mutils[39;00m
[1;32m     18[0m [38;5;28;01mfrom[39;00m [38;5;21;01mutils[39;00m [38;5;28;01mimport[39;00m cols, theme
[1;32m     19[0m [38;5;28;01mimport[39;00m [38;5;21;01mgraphing[39;00m

[0;31mModuleNotFoundError[0m: No module named 'utils'

